name: CI

on:
  release:
    types:
      - prepublished
      - published

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=version;]$(npm version patch)"
        id: info
      - run: echo ${{ steps.info.outputs.version }}
      - run: echo ${{ github.event.release.upload_url }}
